### ISSUE TITLE
使用 Python 调用接口报错

### ISSUE THREAD

**Issue by doublewinter0** [TimothyYe/bing-wallpaper#8]
**你好, 我使用 Python 调用你的接口, 报如下的错误:**
```
Traceback (most recent call last):
  File "C:\Users\erdong\Dev\Scoop\apps\python\current\lib\site-packages\urllib3\connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\erdong\Dev\Scoop\apps\python\current\lib\site-packages\urllib3\util\connection.py", line 96, in create_connection
    raise err
  File "C:\Users\erdong\Dev\Scoop\apps\python\current\lib\site-packages\urllib3\util\connection.py", line 86, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\erdong\Dev\Scoop\apps\python\current\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\erdong\Dev\Scoop\apps\python\current\lib\site-packages\urllib3\connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "C:\Users\erdong\Dev\Scoop\apps\python\current\lib\site-packages\urllib3\connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "C:\Users\erdong\Dev\Scoop\apps\python\current\lib\site-packages\urllib3\connection.py", line 353, in connect
    conn = self._new_conn()
  File "C:\Users\erdong\Dev\Scoop\apps\python\current\lib\site-packages\urllib3\connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000002045BDC95E0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\erdong\Dev\Scoop\apps\python\current\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\erdong\Dev\Scoop\apps\python\current\lib\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "C:\Users\erdong\Dev\Scoop\apps\python\current\lib\site-packages\urllib3\util\retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='bing.biturl.top', port=443): Max retries exceeded with url: /?resolution=3840 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002045BDC95E0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\erdong\bin\wallpaper.py", line 21, in <module>
    bing()
  File "C:\Users\erdong\scripts\py\wp\bg.py", line 18, in bing
    with session.get(url) as pic_info:
  File "C:\Users\erdong\Dev\Scoop\apps\python\current\lib\site-packages\requests\sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\erdong\Dev\Scoop\apps\python\current\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\erdong\Dev\Scoop\apps\python\current\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\erdong\Dev\Scoop\apps\python\current\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='bing.biturl.top', port=443): Max retries exceeded with url: /?resolution=3840 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002045BDC95E0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
```
**Python 版本**
```
Python 3.9.6 (tags/v3.9.6:db3ff76, Jun 28 2021, 15:26:21) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
```

**Comment by TimothyYe** [comment]
这不应该啊，用curl都没问题
![image](https://user-images.githubusercontent.com/860685/129303837-19880f12-1f30-4d0e-bff2-838c444f1e52.png)

**Comment by doublewinter0** [comment]
**应该是网络配置的问题**

**这是我本地网络环境, 直接超时**
![image](https://user-images.githubusercontent.com/22414051/129648678-afb7aaec-6566-466f-9b58-21babbde77d5.png)

**我的服务器就没问题**
![image](https://user-images.githubusercontent.com/22414051/129648738-e912c1e6-7855-4551-a48a-0bfef8fd6710.png)

**Comment by TimothyYe** [comment]
有可能，这个API托管在Cloudflare上

**Comment by TimothyYe** [comment]
![image](https://user-images.githubusercontent.com/860685/129663380-d9ae478e-9f7c-419b-af99-da00eee3f8be.png)

我也登录一台国内的服务器试了一下，应该是最近Cloudflare被干扰了……
